// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/SupenBysz/gf-admin/internal/logic/area"
	_ "github.com/SupenBysz/gf-admin/internal/logic/auth"
	_ "github.com/SupenBysz/gf-admin/internal/logic/bizctx"
	_ "github.com/SupenBysz/gf-admin/internal/logic/captcha"
	_ "github.com/SupenBysz/gf-admin/internal/logic/casbin"
	_ "github.com/SupenBysz/gf-admin/internal/logic/file"
	_ "github.com/SupenBysz/gf-admin/internal/logic/jwt"
	_ "github.com/SupenBysz/gf-admin/internal/logic/middleware"
	_ "github.com/SupenBysz/gf-admin/internal/logic/sdk_baidu"
	_ "github.com/SupenBysz/gf-admin/internal/logic/sys_audit"
	_ "github.com/SupenBysz/gf-admin/internal/logic/sys_logs"
	_ "github.com/SupenBysz/gf-admin/internal/logic/sys_menu"
	_ "github.com/SupenBysz/gf-admin/internal/logic/sys_organization"
	_ "github.com/SupenBysz/gf-admin/internal/logic/sys_permission"
	_ "github.com/SupenBysz/gf-admin/internal/logic/sys_role"
	_ "github.com/SupenBysz/gf-admin/internal/logic/sys_sms"
	_ "github.com/SupenBysz/gf-admin/internal/logic/sys_user"
)
